name: CICD for my application

on:
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Print HELLO WORLD
      run: echo "HELLO, WORLD!"
  say-Bye:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World!"
    
