name:CICD for my application

on:
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Print WELCOME WORLD
      run: echo "WELCOME, WORLD!"
  say-Bye:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World!"
